### ISSUE TITLE
Regression reading catalog from URI between 0.12.4 & 0.13.1

### ISSUE THREAD

**Issue by cmarchand** [ndw/xmlresolver#13] opened 2018-07-04 08:10 UTC
Hello,

we load catalog from a custom URL, `cp:/catalog.xml`, with a URLStreamHandler that implements the protocol as looking in classpath.

With xmlresolver 0.12.4, this was working correctly, but with 0.13.1, we get a `java.net.ConnectionException` :
```
org.xmlresolver.Catalog - I/O exception reading cp:/catalog.xml: java.net.ConnectException: Connection timed out
```
I think I'm going to have problems to get the whole exception stack trace.

Maybe a multiple use of the same `InputSource` ?

Best,
Christophe

**Comment by ndw** [comment] 2018-07-06 20:52
I don't know off the top of my head. That doesn't sound like the obvious culprit though. Same version of Java?

**Comment by ndw** [comment] 2018-07-07 21:55
Hi Christophe,

Can you try with 0.14.0, released today, (it's an experimental release, so I'm not suggesting you put it in production without testing!) and see if the problem has gone away?

I don't expect that it will have, but I did tinker with a some of the http stuff and I updated the httpclient library.

If it's still happening, I think I'm going to need a reproducible test case...

**Comment by AxelCourt** [comment] 2018-07-09 09:39
Hello,

Thanks for the release and the time spent working on it.
Unfortunately it did not do the trick for us, we are getting the same `java.net.ConnectException`. :(

We are working on providing you with a test case (but it could be tricky since we are encountering this error in a Spring XD environment).
We will get back to you soon!

Thanks again,
Axel

**Comment by cmarchand** [comment] 2018-07-09 09:42
Hi Norm,
problem still exists with 0.14.0. But creating a reproductible test case will be a hard task, as we have a lot of Spring stuff on resource loading part. And as holidays impact everybody, we delay this to august.

Thanks, and stay tuned !

Best,
Christophe

**Comment by ndw** [comment] 2018-07-09 10:41
Ok. I've glanced through a diff between 0.12.4 and 0.13.1. There are a bunch of changes, of course, but nothing stands out as a likely culprit. Curiously, `ResourceConnection` where the actual I/O gets done, is unchanged. I also reviewed all the commit messages between 0.12.4 and now. Again, nothing stands out.

Can you try 0.12.5 for me?

**Comment by AxelCourt** [comment] 2018-07-09 16:02
Hi,

I ran the program with version 0.12.5 and it seems to work as expected.
We will try and investigate a bit more to see if we find anything else suspicious and come back to you with a test case.

Thanks,
Axel

**Comment by ndw** [comment] 2018-07-09 16:10
Interesting. I'll help in any way I can, just let me know.

**Comment by ndw** [comment] 2019-02-14 08:54
Any progress on this? If not, I'm tempted to close this as "not reproducible"

**Comment by cmarchand** [comment] 2019-02-14 19:57
Close it as "Not reproductible"'.
If we have again the problem, we will re-open it.

Thanks,
Christophe

**Comment by ndw** [comment] 2019-02-14 20:00
Thanks, Christophe!

**Closed by ndw** 2019-02-14 20:00 UTC
